getByChannel now has pagination
bakaphp/kanvas-packages pull request #58
Opened 2020-10-09 20:19 UTC by rwhite27

2020-10-09 20:23 UTC, arfenis approved these changes

2020-10-09 20:57 UTC, kaioken requested changes

2020-10-09 20:57 UTC, kaioken commented on src/Social/Models/ChannelMessages.php
> +    public function getMessages(Channels $channel, int $page = 1, int $limit = 25, string $orderBy = "id", string $sort = "DESC"): Simple
@rwhite27 you are going to hate me but I was refering to having sort by $sort = 'id|desc' , but this i good enough

2020-10-09 20:57 UTC, kaioken commented on src/Social/Models/ChannelMessages.php
> +        $userData = Di::getDefault()->get('userData');
@rwhite27 use this instead of that https://github.com/bakaphp/baka/blob/0.6/src/Auth/UserProvider.php#L32

2020-10-12 14:18 UTC, kaioken approved these changes

2020-10-12 14:45 UTC, merged