Implementation fixes
bakaphp/kanvas-packages pull request #62
Opened 2020-10-14 23:11 UTC by arfenis

- Remove getInteractionByUser from interactions traits to be used on models/entities.
- Update relationship bettwen message and AppModuleMessage
- Remove is_deleted condition from interactions creation to avoid duplication.
- Send message to UsersFeeds after message creation.
- Create method to get message from an Messageable Interface.
- Create method to get the App Module data from a message.
- Rollback changes on Reactions, now can create and remove reaction with double call.
- Create method to get reactions made by the user from the name of the reaction.
- Create method to remove user reaction. (Flag as deleted).
- Update App Module Message migration, from app_module_id to app_module, to store the namespace and not the id.

2020-10-15 14:06 UTC, rwhite27 approved these changes

2020-10-16 13:50 UTC, kaioken requested changes

2020-10-16 13:50 UTC, kaioken commented on src/Social/Services/Reactions.php
> +    public static function addMessageReaction(string $reaction, UserInterface $user, ModelInterface $entity): Bool
@arfenis Bool should be bool

2020-10-16 13:50 UTC, kaioken commented on src/Social/Services/Reactions.php
> +        if ($reaction->is_deleted) {
@arfenis 
```
 if ($reaction->is_deleted) {
            $reaction->is_deleted = 0;
            $reaction->saveOrFail();
        } else {
            $reaction->is_deleted = 1;
            $reaction->saveOrFail();
        }
```
Should be

```
 if ($reaction->is_deleted) {
            $reaction->is_deleted = 0;
        } else {
            $reaction->is_deleted = 1;
        }
            $reaction->saveOrFail();
```

2020-10-16 16:23 UTC, kaioken approved these changes

2020-10-16 16:23 UTC, kaioken commented
@arfenis approved

2020-10-16 17:21 UTC, merged