Magic import
bakaphp/kanvas-packages pull request #9
Opened 2020-06-12 18:57 UTC by dasdo

2020-06-12 20:12 UTC, kaioken requested changes

2020-06-12 20:12 UTC, kaioken commented on composer.json
> +            "Kanvas\\Libraries\\": "src/",
@dasdo Kanvas\Package Plain should be the and that it you dont need any of the other folder since this is PSR4

2020-06-12 20:12 UTC, kaioken commented on src/MagicImports/Contracts/ImportsTrait.php
> +    public function structure()
@dasdo response type

2020-06-12 20:12 UTC, kaioken commented on src/MagicImports/Imports.php
> +    public function processData(array $data)
@dasdo response type

2020-06-12 20:12 UTC, kaioken commented on src/MagicImports/Imports.php
> +    public function save(array $modelData)
@dasdo response type

2020-06-12 20:12 UTC, kaioken commented on src/MagicImports/Imports.php
> +    public function getReturn($models)
@dasdo doc

2020-06-12 20:12 UTC, kaioken commented on src/MagicImports/Imports.php
> +    public function getClassName($obj)
@dasdo doc and type , also what is this for? why not use the one I created in baka ?
https://github.com/bakaphp/baka/blob/0.5/src/functions.php#L121

2020-06-12 20:12 UTC, kaioken commented on src/MagicImports/Structure.php
> +    public function setRelationships($classBase, $x = true)
@dasdo type, doc and resturn type

2020-06-15 13:50 UTC, arfenis requested changes

2020-06-15 13:50 UTC, arfenis commented on composer.json
> +        "vlucas/phpdotenv": "^2.4"
We need "baka/baka" dependencies because the social packages uses it.

2020-06-16 14:23 UTC, dasdo commented on composer.json
> +        "vlucas/phpdotenv": "^2.4"
I put the dependency back

2020-06-17 18:46 UTC, kaioken requested changes

2020-06-17 18:46 UTC, kaioken commented on src/MagicImports/Imports.php
> +    public function getStructureData($raw, $maps): array
@dasdo type of params

2020-06-17 18:46 UTC, kaioken commented on src/MagicImports/Imports.php
> +    public function saveRelationships($models, Model $model, $relationships) : array
@dasdo use ModelInterface instead of Model

2020-06-19 13:52 UTC, kaioken requested changes

2020-06-19 13:52 UTC, kaioken commented on src/MagicImports/Structure.php
> +    public function setRelationships($classBase, $recursive = true) : array
@dasdo $classbase type

2020-06-19 13:52 UTC, kaioken commented on src/MagicImports/Structure.php
> +    public function setStructure(Model $model): array
@dasdo use interface modelInterface

2020-06-19 14:10 UTC, kaioken requested changes

2020-06-19 14:10 UTC, kaioken commented on src/MagicImports/Imports.php
> +    public function getReturn($models) : array
@dasdo same thing this is a array

2020-06-19 14:10 UTC, kaioken commented on src/MagicImports/Imports.php
> +    public function saveRelationships($models, ModelInterface $model, $relationships) : array
@dasdo same thing this is a array

2020-06-19 14:21 UTC, kaioken requested changes

2020-06-19 14:21 UTC, kaioken commented on src/MagicImports/Structure.php
> +    function __construct(Model $model, $fields = [], $relationship = [])
@dasdo here to modelInterface

2020-06-19 14:23 UTC, kaioken approved these changes

2020-06-19 14:24 UTC, merged